Update new_main.yml

diff --git a/.github/workflows/new_main.yml b/.github/workflows/new_main.yml
--- a/.github/workflows/new_main.yml
+++ b/.github/workflows/new_main.yml
@@ -1,23 +1,30 @@
-name: Node.js CI
+name: 'Docker Build Branch'
 
 on:
-  push:
-    branches: [ master ]
   pull_request:
-    branches: [ master ]
+    types: [ labeled, opened, reopened, synchronize ]
+
+env:
+  REGISTRY: ghcr.io
+  IMAGE_NAME: ${{ github.repository }}
+  PROMTOOL_IMAGE_NAME: sre-promtool
+  PROMTOOL_VERSION: 2.38.0
+  USER: ho-cto
 
 jobs:
-  build:
-
+  publish:
+    name: 'Branch Publish'
+    permissions:
+      contents: read
+      packages: write
+      security-events: write
     runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        node-version: [16.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
-
+    if: contains(github.event.pull_request.labels.*.name, 'smoketest') == true
     steps:
-      - uses: actions/checkout@v2
+      #Checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it.
+      - name: Checkout
+        uses: actions/checkout@v3
+
       - name: Use Node.js for installing Snyk
         uses: actions/setup-node@v2
         with:
@@ -32,10 +39,91 @@ jobs:
 
       - run: snyk auth ${{ secrets.SNYK_TOKEN }}
 
-      - name: use snyk
-        run: | 
-          snyk container test ghcr.io/ho-cto/sre-monitoring-as-code:75d4a190e109a620b331d182f9e89fbf60190134 --app-vulns --nested-jars-depth=5 --file=./monitoring-as-code/Dockerfile --sarif-file-output=snyk.sarif
-      - name: Upload result to GitHub Code Scanning
+        #Logs into Github registry
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v2.0.0
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Calculate metadata
+        id: meta
+        uses: docker/metadata-action@v4
+        with:
+          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+          tags: |
+            type=raw,value=${{ github.event.pull_request.head.sha }}
+      - name: Build container
+        uses: docker/build-push-action@v3
+        with:
+          context: ./monitoring-as-code
+          file: ./monitoring-as-code/Dockerfile
+          push: false
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          build-args: |
+            PACKAGE_TOKEN=${{secrets.GITHUB_TOKEN}}
+            MAC_VERSION='#${{ github.event.number }}'
+      - name: Run monitoring mixin
+        run:  docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data -t ${{ steps.meta.outputs.tags }} -m monitoring -rd -i ${{ github.workspace }}/data/mixin-defs -o ${{ github.workspace }}/data/output
+
+      - name: Run testing mixin
+        run:  docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data -t ${{ steps.meta.outputs.tags }} -m testing -rd -i ${{ github.workspace }}/data/mixin-defs -o ${{ github.workspace }}/data/output
+
+      - name: Run promtool checks
+        run: for FILE in ${{ github.workspace }}/monitoring-as-code/output/prometheus-rules/*-rules.yaml; do docker run -v ${{ github.workspace }}/monitoring-as-code:${{ github.workspace }}/data ${{env.REGISTRY}}/${{env.USER}}/${{env.PROMTOOL_IMAGE_NAME}}:${{env.PROMTOOL_VERSION}} check rules ${{ github.workspace }}/data/output/prometheus-rules/$(basename $FILE); if [ $? -ne 0 ]; then echo "Validation of rules files failed for $(basename $FILE) - exiting"; exit 1; fi done
+
+      - name: Snyk Container Scanning
+        id: snyk-dockerfile
+        run: snyk container test --file=./monitoring-as-code/Dockerfile --app-vulns --sarif-file-output=snyk-container.sarif ${{ steps.meta.outputs.tags }}
+        continue-on-error: true
+      - name: Upload results to GitHub Container Scanning
         uses: github/codeql-action/upload-sarif@v2
         with:
-          sarif_file: snyk.sarif
+          sarif_file: snyk-container.sarif
+
+
+      # Snyk security scan of Docker file and Built Docker Image with unmanaged dependencies
+#      - name: Run Snyk to check Docker file for vulnerabilities
+#        id: snyk-dockerfile
+#        continue-on-error: true
+#        uses: snyk/actions/docker@0.3.0
+#        env:
+#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+#        with:
+#          image: ${{ steps.meta.outputs.tags }}
+##          sarif: snyk.sarif
+#          args: |
+#            --file=./monitoring-as-code/Dockerfile
+#            --severity-threshold=medium
+#            --app-vulns
+##            --sarif-file-output=snyk.sarif
+#
+#      - name: Upload result to GitHub Code Scanning
+#        uses: github/codeql-action/upload-sarif@v2
+#        with:
+#          sarif_file: snyk.sarif
+
+      - name: Check on failures
+        if: steps.snyk-dockerfile.outcome != 'success'
+        run: exit 1
+
+#      - name: Run Snyk to check Docker image for vulnerabilities
+#        id: snyk-image
+#        continue-on-error: true
+#        uses: snyk/actions/docker@0.3.0
+#        env:
+#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+#        with:
+#          image: ${{ steps.meta.outputs.tags }}
+#          args: |
+#            --app-vulns
+#            --severity-threshold=medium
+#
+#      - name: Check on failures
+#        if: steps.snyk-image.outcome != 'success'
+#        run: exit 1
+
+      - name: Push image to GitHub Container Registry
+        run: docker push ${{ steps.meta.outputs.tags }}
